-- NO-OP INTENCIONAL. No agregar sentencias a este archivo.
--
-- Esta migracion nunca se aplico: la anterior (20260727000008) fallaba y cortaba
-- la cadena. Al revisarla, ademas, resulto incorrecta: duplicaba modelo que ya
-- existe en 20260726000001_initial_schema.sql.
--
-- `domain text`      -> el dominio ya se modela con la FK `knowledge_units.domain_id`
--                       contra la tabla `public.domains`, que soporta jerarquia
--                       (parent_id) y responsable (owner_id). Una columna de texto
--                       suelta romperia esa relacion.
-- `dependencies uuid[]` -> las dependencias entre KUs ya viven en la tabla
--                       `public.ku_dependencies`, que permite RLS y integridad
--                       referencial. Un array de uuids no valida nada.
--
-- Para leer el nombre del dominio, hacer join: `select *, domains(name)`.
-- Ver `getKnowledgeUnits` en src/lib/knowledge/actions.ts.
--
-- Se deja como no-op en lugar de borrar el archivo para no alterar la secuencia
-- de versiones en entornos donde ya se hubiera registrado.

select 1;
