-- NO-OP INTENCIONAL. No agregar sentencias a este archivo.
--
-- Originalmente esta migracion hacia `create table public.agents (...)`, pero la
-- tabla ya la crea 20260726000003_agents.sql. Al correr la cadena completa
-- fallaba con "relation already exists" y cortaba las migraciones siguientes
-- (por eso 20260727000009 tampoco llego a aplicarse nunca).
--
-- La definicion valida de `public.agents` es:
--   20260726000003_agents.sql      -> tabla base, RLS, indices, trigger
--   20260726000004_marketplace.sql -> visibility, rating, ratings_count,
--                                     cloned_from, tags
--
-- La version que vivia aca declaraba columnas que NO existen en la base real
-- (`knowledge_ids`, `owner_id`); las correctas son `selected_ku_ids` y
-- `created_by`. Tampoco tenia el check constraint de `status`
-- ('draft','deployed','paused','archived').
--
-- Se deja como no-op en lugar de borrar el archivo para no alterar la secuencia
-- de versiones en entornos donde ya se hubiera registrado.

select 1;
